# Cpp language
language: cpp
sudo: required
dist: trusty

# Compiler selection
compiler:
  - clang
  - gcc
# Enable caching
cache:
  apt: true
# Build matrix
addons:
  apt:
    sources: 
        - george-edison55-cmake-3.x
        - ubuntu-toolchain-r-test
    packages:
        - g++-7
        - gcc-7
        - cmake
        - cmake-data
# Install
install:
  - if [ "$TRAVIS_OS_NAME" = "linux" -a "$CXX" = "g++" ]; then export CXX="g++-7" CC="gcc-7"; fi

# Build steps
script:
  - mkdir build
  - cd build
  - cmake .. && make
