# Cpp language
language: cpp
sudo: required
dist: xenial

# Compiler selection
compiler:
  - clang
  - gcc

# Build matrix
addons:
  apt:
    sources:
        - ubuntu-toolchain-r-test
    packages:
        - g++-8
        - gcc-8

# Install
install:
  - if [ "$TRAVIS_OS_NAME" = "linux" -a "$CXX" = "g++" ]; then export CXX="g++-8" CC="gcc-8"; fi

# Build steps
script:
  - mkdir build
  - cd build
  - cmake .. && make
