version: '0.0.0.{build}'

image: Visual Studio 2019

environment:
  matrix:
  - ARCHITECTURE: "x86"
  - ARCHITECTURE: "x64"

matrix:
  fast_finish: true

install:
- call "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Auxiliary\\Build\\vcvarsall.bat" %ARCHITECTURE%
- cd /D "%APPVEYOR_BUILD_FOLDER%"

before_build:
- cmake -H. -Bbuild -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_MAKE_PROGRAM="C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\IDE\\CommonExtensions\\Microsoft\\CMake\\Ninja\\ninja.exe"

build_script:
- cmake --build build

test: off
